CREATE TABLE IF NOT EXISTS Students (
	studentId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	year INTEGER,
	lastName VARCHAR(50),
	firstName VARCHAR(50),
	numEtudiant INTEGER UNIQUE,
	mail VARCHAR(50),
	token VARCHAR(50),
	step VARCHAR(50))
	DEFAULT CHARSET=utf8;
			
CREATE TABLE IF NOT EXISTS Options (
	optionId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	intitule VARCHAR(50),
	mail VARCHAR(50),
	size INTEGER,
	year INTEGER)
	DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Preferences (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	groupId INTEGER,
	choice INTEGER,
	optionId INTEGER,
	numEtudiant INTEGER)
	DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Repeaters (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	choice INTEGER,
	optionId INTEGER,
	numEtudiant INTEGER)
	DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS GroupOp (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	groupId INTEGER,
	optionId INTEGER)
	DEFAULT CHARSET=utf8;